version: '3'
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - "$STACK_DATA/nextcloud/main:/var/www/html"
      - "$STACK_DATA/nextcloud/config:/var/www/html/config"
      - "$STACK_DATA/nextcloud/apps:/var/www/html/custom_apps"
      - "$STACK_DATA/nextcloud/data:/var/www/html/data"
      - "$MEDIA_LOCATION:/media"
    #  - "$STACK_DIR/configs/radicale:/config/config:ro"
    networks:
      - "webapp"
      - nextcloud
    depends_on:
      - nextcloud-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=leresolver"
      - "traefik.http.middlewares.nextcloudHeaders.headers.contentSecurityPolicy=default-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'"
      - "traefik.http.middlewares.nextcloudHeaders.headers.framedeny=true"
      - "traefik.http.middlewares.nextcloudHeaders.headers.sslredirect=true"
      - "traefik.http.middlewares.nextcloudHeaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloudHeaders.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloudHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloudHeaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nextcloudHeaders.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloudHeaders.headers.stsSeconds=31536000"
      - "traefik.http.routers.nextcloud.middlewares=nextcloudHeaders"
  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-db
    restart: unless-stopped
    networks:
      - nextcloud
    volumes:
      - $STACK_DATA/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
networks:
  nextcloud:
  webapp:
    external:
      name: 'webapp'